import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Header from "@/components/Header";
import Video from "@/components/Video";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// c1 >> #121316
// c2 >> #483b68

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-6 flex flex-col gap-y-20`}>
        <NavBar />
        <div className="min-w-[400px] self-center text-center px-4 py-2 border border-[#483b68] rounded-3xl">
          {/* <a href="#" className="text-sm">
            contact us
          </a> */}
        </div>
        <Header />
        {children}
        <Video />
      </body>
    </html>
  );
}
